### PR TITLE
parameterize Rest Service Address

### PR DESCRIPTION
**Pull request by yvz5**

### CODE REVIEW

**Comment by Dedac** [comment]
Can you add documentation for this in the readme?

**Comment by yvz5** [comment]
ofcourse. I was not able to test it, can you make sure it works as intended ?

**Comment by Dedac** [comment]
Are the directions for testing the extension in the Readme too sparse?  I may need add some more content there if you were not able to build and test your change.

**Comment by yvz5** [comment]
Yeah I have never built a vs code extension before and to be honest even the ms docs did not help. I just gave up on that :)

**Comment by yvz5** [comment]
@Dedac Could you take over from here and test the code ? I need this extension for my project and the deadline is pressuring me. I would love to have this feature released soon. I hope you understand.

**Comment by Dedac** [comment]
@yvz5 I made some changes to your original idea, but you can now sub into the parameters with field values with $(Custom.FieldName)
It is published as 0.3.3

**Pull request merged**
